name: "CI/CD"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DIST_FOLDER: dist

jobs:
  ci:
    name: CI (Build, UnitTests)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore
    - name: UnitTests
      run: | 
        dotnet test src/VoucherSystem.TestsUnit --no-build --verbosity normal
    - name: Publish
        run: |
          dotnet publish src/VoucherSystem/VoucherSystem.csproj --configuration release --output dist
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIST_FOLDER }}
          path: dist
          if-no-files-found: error

  deploy_t:
    name: Deploy to Test environment
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
        with:
          name: ${{ env.DIST_FOLDER }}
          path: ${{ env.DIST_FOLDER }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP_TEST_GROUP }}
    - name: Create environment
      run: >
        az deployment group create 
        --resource-group voucher-system-t 
        --template-file infra/main.bicep
        --name infra-${{github.sha}} 
        --parameters stage=t
        --parameters baseName=voucher-sys
        --parameters hash=${{github.sha}} 
        --parameters repository=https://github.com/${{ github.repository }}
      - name: Zip
        run: |
          zip -r dist.zip ${{ env.DIST_FOLDER }} 
      - name: Azure WebApp Deploy
        run: >
          az webapp deployment source config-zip 
          --subscription bc5ef57e-1674-4d98-aa20-41f14f348235
          --resource-group voucher-system-t
          --name voucher-sys-t
          --src dist.zip

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [deploy_t]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet restore src/VoucherSystem.TestsIntegration
    - name: Build
      run: |
        dotnet build src/VoucherSystem.TestsIntegration --no-restore
    - name: IntegrationTests
      run: | 
        URL_TO_WEB_API=https://voucher-sys-t.azurewebsites.net dotnet test src/VoucherSystem.TestsIntegration --no-build --verbosity normal

  deploy_p:
    name: Deploy to Production environment
    runs-on: ubuntu-latest
    needs: [integration_tests]
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP_PROD_GROUP }}
    - name: Create environment
      run: >
        az deployment group create 
        --resource-group voucher-system-p 
        --template-file infra/main.bicep
        --name infra-${{github.sha}} 
        --parameters stage=p
        --parameters baseName=voucher-sys
        --parameters hash=${{github.sha}} 
        --parameters repository=https://github.com/${{ github.repository }}
